-- =============================================================
-- IoT Smart Energy Management Dashboard - Database Setup
-- =============================================================
-- Run this script BEFORE launching the application.
-- Default credentials: admin / admin123
-- =============================================================

-- Create database
CREATE DATABASE IF NOT EXISTS iot_dashboard
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE iot_dashboard;

-- =============================================================
-- TABLE: devices
-- Stores static metadata about simulated edge devices
-- =============================================================
CREATE TABLE IF NOT EXISTS devices (
    device_id   SMALLINT     NOT NULL AUTO_INCREMENT,
    device_name VARCHAR(100) NOT NULL,
    location    VARCHAR(100) NOT NULL DEFAULT 'Unknown',
    status      TINYINT      NOT NULL DEFAULT 1 COMMENT '1=Active, 0=Inactive',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- TABLE: sensor_types
-- Classifies the type of sensor metric being stored
-- =============================================================
CREATE TABLE IF NOT EXISTS sensor_types (
    type_id     TINYINT      NOT NULL AUTO_INCREMENT,
    measurement VARCHAR(50)  NOT NULL,
    unit        VARCHAR(20)  NOT NULL,
    PRIMARY KEY (type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- TABLE: sensor_data (main fact table for time-series telemetry)
-- Uses TIMESTAMP (4 bytes) vs DATETIME (8 bytes) for efficiency
-- Uses FLOAT  (4 bytes) vs DOUBLE  (8 bytes) — 7 sig. digits sufficient
-- =============================================================
CREATE TABLE IF NOT EXISTS sensor_data (
    reading_id  BIGINT    NOT NULL AUTO_INCREMENT,
    device_id   SMALLINT  NOT NULL,
    type_id     TINYINT   NOT NULL,
    timestamp   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    value       FLOAT     NOT NULL,
    PRIMARY KEY (reading_id),
    INDEX idx_device_type_time (device_id, type_id, timestamp),
    INDEX idx_timestamp        (timestamp),
    FOREIGN KEY (device_id) REFERENCES devices(device_id)  ON DELETE CASCADE,
    FOREIGN KEY (type_id)   REFERENCES sensor_types(type_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- TABLE: admin_users
-- Stores hashed admin credentials (BCrypt)
-- =============================================================
CREATE TABLE IF NOT EXISTS admin_users (
    user_id       INT          NOT NULL AUTO_INCREMENT,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) DEFAULT NULL,
    last_login    TIMESTAMP    NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- SEED DATA: Default devices
-- =============================================================
INSERT IGNORE INTO devices (device_id, device_name, location, status) VALUES
(1, 'Smart Meter A1',    'Building A - Floor 1', 1),
(2, 'Smart Meter B1',    'Building B - Floor 1', 1),
(3, 'Industrial Sensor', 'Server Room',          1),
(4, 'Grid Monitor',      'Main Distribution',    1);

-- =============================================================
-- SEED DATA: Sensor types
-- =============================================================
INSERT IGNORE INTO sensor_types (type_id, measurement, unit) VALUES
(1, 'Temperature',    '°C'),
(2, 'Humidity',       '%'),
(3, 'Voltage',        'V'),
(4, 'Active Power',   'W');

-- =============================================================
-- SEED DATA: Default admin user
-- Username : admin
-- Password : admin123
-- Hash is BCrypt with 10 rounds (generated by the Java application)
-- The application's DatabaseSetup class will insert this on first run.
-- If you want to insert manually, run the Java setup utility first.
-- =============================================================

-- Verify setup
SELECT 'Database setup complete!' AS status;
SELECT TABLE_NAME, TABLE_ROWS
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = 'iot_dashboard';
