-- =============================================================
-- IoT Smart Energy Management Dashboard - Database Setup
-- =============================================================
-- Run this script BEFORE launching the application.
-- Default credentials: admin / admin123
-- =============================================================

-- Create database
CREATE DATABASE IF NOT EXISTS iot_dashboard
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE iot_dashboard;

-- =============================================================
-- TABLE 1: devices
-- Stores static metadata about simulated edge devices
-- =============================================================
CREATE TABLE IF NOT EXISTS devices (
    device_id   SMALLINT     NOT NULL AUTO_INCREMENT,
    device_name VARCHAR(100) NOT NULL,
    location    VARCHAR(100) NOT NULL DEFAULT 'Unknown',
    status      TINYINT      NOT NULL DEFAULT 1 COMMENT '1=Active, 0=Inactive',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- TABLE 2: sensor_types
-- Classifies the type of sensor metric being stored
-- =============================================================
CREATE TABLE IF NOT EXISTS sensor_types (
    type_id     TINYINT      NOT NULL AUTO_INCREMENT,
    measurement VARCHAR(50)  NOT NULL,
    unit        VARCHAR(20)  NOT NULL,
    PRIMARY KEY (type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- TABLE 3: sensor_data (main fact table for time-series telemetry)
-- Uses TIMESTAMP (4 bytes) vs DATETIME (8 bytes) for efficiency
-- Uses FLOAT  (4 bytes) vs DOUBLE  (8 bytes) — 7 sig. digits sufficient
-- =============================================================
CREATE TABLE IF NOT EXISTS sensor_data (
    reading_id  BIGINT    NOT NULL AUTO_INCREMENT,
    device_id   SMALLINT  NOT NULL,
    type_id     TINYINT   NOT NULL,
    timestamp   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    value       FLOAT     NOT NULL,
    PRIMARY KEY (reading_id),
    INDEX idx_device_type_time (device_id, type_id, timestamp),
    INDEX idx_timestamp        (timestamp),
    FOREIGN KEY (device_id) REFERENCES devices(device_id)  ON DELETE CASCADE,
    FOREIGN KEY (type_id)   REFERENCES sensor_types(type_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- TABLE 4: admin_users
-- Stores hashed admin credentials (BCrypt)
-- =============================================================
CREATE TABLE IF NOT EXISTS admin_users (
    user_id       INT          NOT NULL AUTO_INCREMENT,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) DEFAULT NULL,
    last_login    TIMESTAMP    NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- TABLE 5: alerts
-- Stores threshold-violation alerts generated by the trigger.
-- is_resolved: 0 = active, 1 = acknowledged/resolved
-- =============================================================
CREATE TABLE IF NOT EXISTS alerts (
    alert_id      INT          NOT NULL AUTO_INCREMENT,
    device_id     SMALLINT     NOT NULL,
    type_id       TINYINT      NOT NULL,
    alert_message VARCHAR(255) NOT NULL,
    threshold_val FLOAT        NOT NULL,
    actual_val    FLOAT        NOT NULL,
    is_resolved   TINYINT      NOT NULL DEFAULT 0 COMMENT '0=Active, 1=Resolved',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (alert_id),
    INDEX idx_alert_device   (device_id),
    INDEX idx_alert_resolved (is_resolved),
    FOREIGN KEY (device_id) REFERENCES devices(device_id)  ON DELETE CASCADE,
    FOREIGN KEY (type_id)   REFERENCES sensor_types(type_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =============================================================
-- SEED DATA: Default devices
-- =============================================================
INSERT IGNORE INTO devices (device_id, device_name, location, status) VALUES
(1, 'Smart Meter A1',    'Building A - Floor 1', 1),
(2, 'Smart Meter B1',    'Building B - Floor 1', 1),
(3, 'Industrial Sensor', 'Server Room',          1),
(4, 'Grid Monitor',      'Main Distribution',    1);

-- =============================================================
-- SEED DATA: Sensor types
-- =============================================================
INSERT IGNORE INTO sensor_types (type_id, measurement, unit) VALUES
(1, 'Temperature',    '°C'),
(2, 'Humidity',       '%'),
(3, 'Voltage',        'V'),
(4, 'Active Power',   'W');

-- =============================================================
-- TRIGGER: trg_high_sensor_alert
-- Fires AFTER every INSERT on sensor_data.
-- If the reading exceeds a predefined threshold for its type,
-- an alert row is automatically created in the alerts table.
-- Thresholds: Temperature > 45°C, Humidity > 90%,
--             Voltage > 250V, Active Power > 3500W
-- =============================================================
DROP TRIGGER IF EXISTS trg_high_sensor_alert;

DELIMITER $$

CREATE TRIGGER trg_high_sensor_alert
AFTER INSERT ON sensor_data
FOR EACH ROW
BEGIN
    DECLARE v_threshold FLOAT DEFAULT NULL;

    SET v_threshold = CASE NEW.type_id
        WHEN 1 THEN 45.0    -- Temperature threshold (°C)
        WHEN 2 THEN 90.0    -- Humidity threshold (%)
        WHEN 3 THEN 250.0   -- Voltage threshold (V)
        WHEN 4 THEN 3500.0  -- Active Power threshold (W)
        ELSE NULL
    END;

    IF v_threshold IS NOT NULL AND NEW.value > v_threshold THEN
        INSERT INTO alerts
            (device_id, type_id, alert_message, threshold_val, actual_val)
        VALUES (
            NEW.device_id,
            NEW.type_id,
            CONCAT('ALERT: Sensor type ', NEW.type_id,
                   ' on device ', NEW.device_id,
                   ' — value=', ROUND(NEW.value, 2),
                   ' exceeds threshold=', v_threshold),
            v_threshold,
            NEW.value
        );
    END IF;
END$$

DELIMITER ;

-- =============================================================
-- STORED PROCEDURE: GetSensorStats
-- Returns aggregated statistics (count, avg, min, max, stddev)
-- for a given sensor type over the last N hours.
-- Usage: CALL GetSensorStats(1, 24);  -- type_id=1 (Temp), last 24h
-- =============================================================
DROP PROCEDURE IF EXISTS GetSensorStats;

DELIMITER $$

CREATE PROCEDURE GetSensorStats(
    IN  p_type_id TINYINT,
    IN  p_hours   INT
)
BEGIN
    SELECT
        st.measurement                   AS sensor_type,
        st.unit                          AS unit,
        COUNT(sd.reading_id)             AS total_readings,
        ROUND(AVG(sd.value), 2)          AS avg_value,
        ROUND(MIN(sd.value), 2)          AS min_value,
        ROUND(MAX(sd.value), 2)          AS max_value,
        ROUND(STDDEV(sd.value), 2)       AS std_dev,
        MAX(sd.timestamp)                AS last_reading_at
    FROM sensor_data  sd
    JOIN sensor_types st ON sd.type_id = st.type_id
    WHERE sd.type_id  = p_type_id
      AND sd.timestamp >= NOW() - INTERVAL p_hours HOUR;
END$$

DELIMITER ;

-- =============================================================
-- DDL: ALTER TABLE
-- Adds ip_address column to devices after initial creation.
-- This demonstrates the ALTER command required by the DDL section.
-- =============================================================
ALTER TABLE devices
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(45) DEFAULT NULL
        COMMENT 'Optional IP address of the edge device';

-- =============================================================
-- DDL: CHECK CONSTRAINTS (Assertions)
-- MySQL 8.0.16+ enforces CHECK constraints.
-- These act as assertion-style data-integrity rules.
-- Note: SQL standard ASSERT statements are not supported by
-- MySQL; CHECK constraints serve the same purpose.
-- =============================================================
ALTER TABLE devices
    ADD CONSTRAINT chk_device_status CHECK (status IN (0, 1));

ALTER TABLE alerts
    ADD CONSTRAINT chk_alert_resolved CHECK (is_resolved IN (0, 1));

-- =============================================================
-- ADVANCED SQL: VIEW — vw_active_alerts
-- Joins alerts, devices, and sensor_types into a single
-- readable view. Queried by the application to display the
-- active alerts panel without repeating the JOIN logic.
-- =============================================================
CREATE OR REPLACE VIEW vw_active_alerts AS
SELECT
    a.alert_id,
    d.device_name,
    d.location,
    st.measurement,
    st.unit,
    a.alert_message,
    a.actual_val,
    a.threshold_val,
    a.created_at
FROM   alerts       a
JOIN   devices      d  ON a.device_id = d.device_id
JOIN   sensor_types st ON a.type_id   = st.type_id
WHERE  a.is_resolved = 0
ORDER  BY a.created_at DESC;

-- =============================================================
-- NESTED QUERY EXAMPLE
-- Retrieve devices that currently have at least one active alert.
-- Uses a correlated subquery (IN with SELECT).
-- Demonstrates nested/subquery requirement from Chapter 6.
-- =============================================================
-- SELECT device_id, device_name, location
-- FROM   devices
-- WHERE  device_id IN (
--            SELECT DISTINCT device_id
--            FROM   alerts
--            WHERE  is_resolved = 0
--        );

-- =============================================================
-- DML EXAMPLES: UPDATE and DELETE
-- (These demonstrate full CRUD compliance.)
-- =============================================================

-- UPDATE example: deactivate a device by ID
-- UPDATE devices SET status = 0 WHERE device_id = 4;

-- UPDATE example: resolve an alert
-- UPDATE alerts SET is_resolved = 1 WHERE alert_id = 1;

-- DELETE example: remove readings older than 7 days
-- DELETE FROM sensor_data WHERE timestamp < NOW() - INTERVAL 7 DAY;

-- DELETE example: clear all resolved alerts
-- DELETE FROM alerts WHERE is_resolved = 1;

-- =============================================================
-- Verify setup
-- =============================================================
SELECT 'Database setup complete!' AS status;

SELECT TABLE_NAME, TABLE_ROWS
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = 'iot_dashboard';

-- Verify trigger
SELECT TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE
FROM information_schema.TRIGGERS
WHERE TRIGGER_SCHEMA = 'iot_dashboard';

-- Verify stored procedure
SELECT ROUTINE_NAME, ROUTINE_TYPE
FROM information_schema.ROUTINES
WHERE ROUTINE_SCHEMA = 'iot_dashboard';
